services:

  mosquitto:
    build: docker/mosquitto
    volumes:
      - ./docker/mosquitto/config/:/mosquitto/config/
    ports:
      - '1883:1883'
      - '9001:9001'
    expose:
      - '1883'
      - '9001'

  db:
    build: docker/db
    volumes:
      - ./docker/db/tmp:/var/lib/postgresql/data/
    ports:
      - '5400:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=webster
      - POSTGRES_PASSWORD=pass123

  app:
    build: app
    ports:
      - '80:80'
    expose:
      - '80'
    depends_on:
      - mosquitto
      - db
    environment:
      - DB_URL=postgres://webster:pass123@db:5432/backend
